# Generated by Django 5.1.3 on 2024-11-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_senha_hospede_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospede',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='hospede',
            name='user_permissions',
        ),
    ]
