# Generated by Django 5.1.3 on 2024-11-27 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_hospede_groups_remove_hospede_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospede',
            old_name='username',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='hospede',
            old_name='password',
            new_name='senha',
        ),
    ]
