# Generated by Django 5.1.3 on 2024-11-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_hospede_nome_alter_hospede_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospede',
            name='nome',
        ),
    ]
