# Generated by Django 5.1.3 on 2024-11-29 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_tipoquarto_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
